// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

package main
import "fmt"

func main() {
    var sum int = 0
    var lastFib int = 1
    var temp int = 1

    for curFib := 2; curFib < 4000000; curFib += lastFib {
    	lastFib = temp
    	if curFib % 2 == 0 {
    		sum += curFib
    	}
    	temp = curFib
    }

    fmt.Println(sum)
}