# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

# ----------------------------------------------------
# 
# This Version is slow because it is no memoized
f = ->(x){ x < 2 ? x : f[x-1] + f[x-2] }

index = 0
sum = 0
while f[index] <= 4_000_000 do
	sum += (f[index] % 2 == 0)? f[index] : 0
	index += 1
end
puts sum